### PR TITLE
Better json

### PR DESCRIPTION
**Pull request by FroggyPanda**
This addition lets users change the properties that are supposed to be json to custom json instead of the generic json type that supabase adds.

To use this, add the `json` property to your `.betterrc.json` file or `betterConfig` in your `package.json` .  It can be used like so:

```json
{
  "input": "test.ts",
  "output": "test2.ts",
  "singular": true,
  "json": {
    "guild": {
      "level_ranks": {
        "role_id": "string",
        "level": "number"
      }
    }
  }
}
```
This will have the generator crawl through the database interface and look for the property `level_ranks` under the `guild` table.

So far, I am running into the issue of not being able to actually change the type on the property but I am able to find the text in the file and replace it outright (this does skip the process of actually making sure that the property is in the correct table).

Any help is greatly appreciated.

### CODE REVIEW

**Comment by FroggyPanda** [comment]
currently have the custom json to be read in from the config file and package json only, but this comes with the bottleneck of limiting how the types are made and the ugliness of having the custom types look like this:
```json
{
  "input": "beforeSchema.ts",
  "output": "afterSchema.ts",
  "json": {
    "todos": {
      "tags": {
        "tag_name": "string",
        "hex_color": "string"
      }
    }
  }
}
```
Any suggestions that might improve upon this is greatly appreciated.

**Comment by gulfaraz** [comment]
@FroggyPanda have you considered making the json property be a path to a file?

**Comment by FroggyPanda** [comment]
> @.FroggyPanda have you considered making the json property be a path to a file?

@gulfaraz I like the idea. What did you have in mind?

**Comment by gulfaraz** [comment]
If the json definitions are usually of significant size (+5 keys), then using [your example](https://github.com/FroggyPanda/better-supabase-types/pull/20#issuecomment-1645797650)

```json
{
  "input": "beforeSchema.ts",
  "output": "afterSchema.ts",
  "json":  "jsonConfig.json"
}
```

where `jsonConfig.json` is,

```json
{
  "todos": {
    "tags": {
      "tag_name": "string",
      "hex_color": "string"
    }
  }
}
```

I find this to be more elegant than keeping the config inside the same file.

**Pull request closed without merging**
