### PR TITLE
added prettier formatting functionality to the tool

### PR DESCRIPTION
**Pull request by barrymichaeldoyle**
This adds adds an option to the tool to take in the path to the prettier file and format the generated types (if that `prettier` option is provided).

Let me know if you'd like me to tweak this at all :)

### CODE REVIEW

**Comment by FroggyPanda** [comment]
Thank you so much for implementing this!

One minor change is that I would like to have `-p` to not require an argument and have it be default to `.prettierrc`  and then if it does have an argument then use that.

For example:
```bash
npx better-supabase-types -i ./scehma.ts -o ./newsSchema.ts -p
```
or
```bash
npx better-supabase-types -i ./scehma.ts -o ./newsSchema.ts -p ./weird/file/path/for/.prettierrc
```

**Comment by FroggyPanda** [comment]
Oh and bump the version up to `1.1.0` (or `2.0.0`? I'm not too sure trying follow [this guide](https://github.com/MLSDev/development-standards/blob/master/common/versioning.md#how-to-track-version-numbers-in-source-code))!!!  You deserve to bump that version up!

**Comment by barrymichaeldoyle** [comment]
Sounds good! Will update that, going to bump to version 1.1.0 since it
doesn’t break existing functionality ;)

**Comment by barrymichaeldoyle** [comment]
Done :) I've also updated the readme to cater for that `force` functionality you added in,

**Pull request merged**
