### PR TITLE
feat: converted table name to PascalCase per TypeScript standards

### LINKED ISSUE #5: Adding PascalCase support
Supabase advises to use `snake_case` for table names, but the standard for types in Typescript is usually `PascalCase`. It would be neat if the generated types were `PascalCased`, instead of the currently `Something_between` the two. Thanks for the package, it is in my workflow already.

### PR DESCRIPTION
**Pull request by barrymichaeldoyle**
This resolves: #5

### CODE REVIEW

**Comment by FroggyPanda** [comment]
Everything looks good! Just add `toPascalCase.ts` to `utils/index.ts` please.

**Comment by barrymichaeldoyle** [comment]
Done :)

**Comment by TimurKr** [comment]
Just a question, this seems like a breaking change, shouldn't it be `v2.0.0` already?

**Comment by barrymichaeldoyle** [comment]
Fair enough, that's true, I'll bump it to v2 then.

**Pull request merged**
