### PR TITLE
try to support Database as either interface or type alias

### LINKED ISSUE #31: Issue parsing types from `supabase gen types`
I'm seeing the following issue when running `npx better-supabase-types -i types/supabase.ts -f`

```
> common@1.0.0 supabase-types
> npx supabase gen types typescript --project-id *********> types/supabase.ts && npx better-supabase-types -i types/supabase.ts -f

/Users/santiago/.npm/_npx/269fea24060d8ca4/node_modules/@ts-morph/common/dist/ts-morph-common.js:438
            throw new InvalidOperationError(typeof errorMessage === "string" ? errorMessage : errorMessage(), node);
                  ^

InvalidOperationError: Expected to find interface named 'Database'.
```

This seems to be happening because `npx supabase gen types` is now returning a type, and better-supabase-types is looking for an interface. As far as I can I haven't updated the supabase cli, so not sure why the sudden change, but perhaps better-supabase-types should support both? 

Here is the difference in types that is causing the issue:
Screenshot 2024-02-13 at 1 45 08 PM

### PR DESCRIPTION
**Pull request by kwbauson**
An attempt to fix https://github.com/FroggyPanda/better-supabase-types/issues/31

### CODE REVIEW

**Comment by FroggyPanda** [comment]
Thank you so much for this!  I was having a really hard time figuring out how in the world to use `ts-morph` and glad you were able to figure it out.

**Comment by FroggyPanda** [comment]
Oh and do make sure to bump the patch in the `project.json` and everything will be good to go 👍

**Comment by kwbauson** [comment]
Ok bumped the patch! I'm not at my computer so I didn't test it :sweat_smile: so hopefully there wasn't anything else to do

**Comment by FroggyPanda** [comment]
> Ok bumped the patch! I'm not at my computer so I didn't test it 😅 so hopefully there wasn't anything else to do

🤞 from what I tested out it seems to all be good.  I am going to be making a new PR to add some tests to this library to make sure future changes don't break anything.

**Comment by PixsaOJ** [comment]
Could we publish the new version on NPM please?

**Comment by FroggyPanda** [comment]
> Could we publish the new version on NPM please?

I will once I, or someone else, can figure out why #33 is occurring.  That issue seemed to have occurred from making the change to support either `interface` or `type`.

**Pull request merged**
